# fly.toml app configuration file generated for telegram-miniapp on 2024-05-27T16:39:14+07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'g3-v2-stg-backend'
primary_region = 'sin'

[build]
dockerfile = "../apps/g3-backend/Dockerfile"

[env]
NEXT_PUBLIC_G3_ENV = "staging"

[[vm]]
memory = '2gb'
cpu_kind = 'shared'
cpus = 2

[http_service]
internal_port = 3200
force_https = true
auto_stop_machines = true
auto_start_machines = true
min_machines_running = 0
[[http_service.checks]]
grace_period = "60s"
interval = "15s"
method = "GET"
timeout = "10s"
path = "/"
