# Same docker file with the centre backend
version: "3"
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: johndoe
      POSTGRES_PASSWORD: randompassword
      POSTGRES_DB: mydb
    volumes:
      - ./g3chain_db_data:/var/lib/postgresql
    ports:
      - 5432:5432
  redis:
    image: redis
    ports:
      - 6379:6379
    restart: always

volumes:
  g3_relayer_mock:
