name: Fly Deploy
on:
  push:
    branches:
      - main    # change to main if needed
      - tin/setup-fly
jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    concurrency: deploy-group    # optional: ensure only one action runs at a time
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --local-only --build-arg TURBO_TEAM="${{ secrets.TURBO_TEAM }}" --build-arg TURBO_TOKEN="${{ secrets.TURBO_TOKEN }}" -c ../../fly.worker.toml
      - run: flyctl deploy --local-only --build-arg TURBO_TEAM="${{ secrets.TURBO_TEAM }}" --build-arg TURBO_TOKEN="${{ secrets.TURBO_TOKEN }}" -c ../../fly.bot.toml
    env:
      FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
